name: Upload Python Package

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build-all:

    strategy:
      fail-fast: false
      matrix:
        # python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout pyradiance
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.20.0
      env:
        CIBW_BUILD: "cp313-*"
        CIBW_SKIP: "*-win32 *-manylinux_i686"
        CIBW_ARCHS_LINUX: "x86_64"
        CIBW_ARCHS_MACOS: "x86_64 arm64"
        CIBW_ARCHS_WINDOWS: "AMD64"
        # Set a newer macOS deployment target to support modern C++ features
        # required by dependencies like nanobind.
        CIBW_MACOSX_DEPLOYMENT_TARGET: "10.15"
        CIBW_TEST_COMMAND: ""
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
        CIBW_TEST_SKIP: "*-win*"

    - name: Upload wheels to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./wheelhouse/*.whl
        tag_name: dist-${{ matrix.os }}-python-tag
        name: Release dist-${{ matrix.os }}-python
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        packages_dir: wheelhouse

